# Generated by Django 5.0.3 on 2024-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=20)),
                ('car_price', models.IntegerField()),
                ('car_number', models.IntegerField()),
                ('sunroof', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
